//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace lcspto_mvc
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataModel object using the connection string found in the 'DataModel' section of the application configuration file.
        /// </summary>
        public DataModel() : base("name=DataModel", "DataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModel object.
        /// </summary>
        public DataModel(string connectionString) : base(connectionString, "DataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModel object.
        /// </summary>
        public DataModel(EntityConnection connection) : base(connection, "DataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<calendaritem> calendaritems
        {
            get
            {
                if ((_calendaritems == null))
                {
                    _calendaritems = base.CreateObjectSet<calendaritem>("calendaritems");
                }
                return _calendaritems;
            }
        }
        private ObjectSet<calendaritem> _calendaritems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<form_fields> form_fields
        {
            get
            {
                if ((_form_fields == null))
                {
                    _form_fields = base.CreateObjectSet<form_fields>("form_fields");
                }
                return _form_fields;
            }
        }
        private ObjectSet<form_fields> _form_fields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<form_responses> form_responses
        {
            get
            {
                if ((_form_responses == null))
                {
                    _form_responses = base.CreateObjectSet<form_responses>("form_responses");
                }
                return _form_responses;
            }
        }
        private ObjectSet<form_responses> _form_responses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<form> forms
        {
            get
            {
                if ((_forms == null))
                {
                    _forms = base.CreateObjectSet<form>("forms");
                }
                return _forms;
            }
        }
        private ObjectSet<form> _forms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<news> news
        {
            get
            {
                if ((_news == null))
                {
                    _news = base.CreateObjectSet<news>("news");
                }
                return _news;
            }
        }
        private ObjectSet<news> _news;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<content> contents
        {
            get
            {
                if ((_contents == null))
                {
                    _contents = base.CreateObjectSet<content>("contents");
                }
                return _contents;
            }
        }
        private ObjectSet<content> _contents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<photo_propertycache> photo_propertycache
        {
            get
            {
                if ((_photo_propertycache == null))
                {
                    _photo_propertycache = base.CreateObjectSet<photo_propertycache>("photo_propertycache");
                }
                return _photo_propertycache;
            }
        }
        private ObjectSet<photo_propertycache> _photo_propertycache;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the calendaritems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocalendaritems(calendaritem calendaritem)
        {
            base.AddObject("calendaritems", calendaritem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the form_fields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToform_fields(form_fields form_fields)
        {
            base.AddObject("form_fields", form_fields);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the form_responses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToform_responses(form_responses form_responses)
        {
            base.AddObject("form_responses", form_responses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToforms(form form)
        {
            base.AddObject("forms", form);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the news EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonews(news news)
        {
            base.AddObject("news", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontents(content content)
        {
            base.AddObject("contents", content);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the photo_propertycache EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTophoto_propertycache(photo_propertycache photo_propertycache)
        {
            base.AddObject("photo_propertycache", photo_propertycache);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="calendaritem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class calendaritem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new calendaritem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="details">Initial value of the Details property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static calendaritem Createcalendaritem(global::System.Int32 id, global::System.String name, global::System.String details, global::System.DateTime date)
        {
            calendaritem calendaritem = new calendaritem();
            calendaritem.ID = id;
            calendaritem.Name = name;
            calendaritem.Details = details;
            calendaritem.Date = date;
            return calendaritem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details;
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="content")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class content : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new content object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="parentPageName">Initial value of the ParentPageName property.</param>
        /// <param name="pageName">Initial value of the PageName property.</param>
        /// <param name="htmlTitle">Initial value of the HtmlTitle property.</param>
        /// <param name="htmlText">Initial value of the HtmlText property.</param>
        /// <param name="loginRequired">Initial value of the LoginRequired property.</param>
        public static content Createcontent(global::System.Int64 id, global::System.String parentPageName, global::System.String pageName, global::System.String htmlTitle, global::System.String htmlText, global::System.Boolean loginRequired)
        {
            content content = new content();
            content.ID = id;
            content.ParentPageName = parentPageName;
            content.PageName = pageName;
            content.HtmlTitle = htmlTitle;
            content.HtmlText = htmlText;
            content.LoginRequired = loginRequired;
            return content;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentPageName
        {
            get
            {
                return _ParentPageName;
            }
            set
            {
                OnParentPageNameChanging(value);
                ReportPropertyChanging("ParentPageName");
                _ParentPageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParentPageName");
                OnParentPageNameChanged();
            }
        }
        private global::System.String _ParentPageName;
        partial void OnParentPageNameChanging(global::System.String value);
        partial void OnParentPageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PageName
        {
            get
            {
                return _PageName;
            }
            set
            {
                OnPageNameChanging(value);
                ReportPropertyChanging("PageName");
                _PageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PageName");
                OnPageNameChanged();
            }
        }
        private global::System.String _PageName;
        partial void OnPageNameChanging(global::System.String value);
        partial void OnPageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HtmlTitle
        {
            get
            {
                return _HtmlTitle;
            }
            set
            {
                OnHtmlTitleChanging(value);
                ReportPropertyChanging("HtmlTitle");
                _HtmlTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HtmlTitle");
                OnHtmlTitleChanged();
            }
        }
        private global::System.String _HtmlTitle;
        partial void OnHtmlTitleChanging(global::System.String value);
        partial void OnHtmlTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HtmlText
        {
            get
            {
                return _HtmlText;
            }
            set
            {
                OnHtmlTextChanging(value);
                ReportPropertyChanging("HtmlText");
                _HtmlText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HtmlText");
                OnHtmlTextChanged();
            }
        }
        private global::System.String _HtmlText;
        partial void OnHtmlTextChanging(global::System.String value);
        partial void OnHtmlTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoginRequired
        {
            get
            {
                return _LoginRequired;
            }
            set
            {
                OnLoginRequiredChanging(value);
                ReportPropertyChanging("LoginRequired");
                _LoginRequired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginRequired");
                OnLoginRequiredChanged();
            }
        }
        private global::System.Boolean _LoginRequired;
        partial void OnLoginRequiredChanging(global::System.Boolean value);
        partial void OnLoginRequiredChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new form object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="formName">Initial value of the FormName property.</param>
        /// <param name="emailResponsesTo">Initial value of the EmailResponsesTo property.</param>
        /// <param name="saveResponses">Initial value of the SaveResponses property.</param>
        public static form Createform(global::System.Int32 id, global::System.String formName, global::System.String emailResponsesTo, global::System.Boolean saveResponses)
        {
            form form = new form();
            form.ID = id;
            form.FormName = formName;
            form.EmailResponsesTo = emailResponsesTo;
            form.SaveResponses = saveResponses;
            return form;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FormName
        {
            get
            {
                return _FormName;
            }
            set
            {
                OnFormNameChanging(value);
                ReportPropertyChanging("FormName");
                _FormName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FormName");
                OnFormNameChanged();
            }
        }
        private global::System.String _FormName;
        partial void OnFormNameChanging(global::System.String value);
        partial void OnFormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailResponsesTo
        {
            get
            {
                return _EmailResponsesTo;
            }
            set
            {
                OnEmailResponsesToChanging(value);
                ReportPropertyChanging("EmailResponsesTo");
                _EmailResponsesTo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailResponsesTo");
                OnEmailResponsesToChanged();
            }
        }
        private global::System.String _EmailResponsesTo;
        partial void OnEmailResponsesToChanging(global::System.String value);
        partial void OnEmailResponsesToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SaveResponses
        {
            get
            {
                return _SaveResponses;
            }
            set
            {
                OnSaveResponsesChanging(value);
                ReportPropertyChanging("SaveResponses");
                _SaveResponses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaveResponses");
                OnSaveResponsesChanged();
            }
        }
        private global::System.Boolean _SaveResponses;
        partial void OnSaveResponsesChanging(global::System.Boolean value);
        partial void OnSaveResponsesChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="form_fields")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class form_fields : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new form_fields object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="formID">Initial value of the FormID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="inputType">Initial value of the InputType property.</param>
        /// <param name="required">Initial value of the Required property.</param>
        public static form_fields Createform_fields(global::System.Int32 id, global::System.Int32 formID, global::System.String name, global::System.String inputType, global::System.Boolean required)
        {
            form_fields form_fields = new form_fields();
            form_fields.ID = id;
            form_fields.FormID = formID;
            form_fields.Name = name;
            form_fields.InputType = inputType;
            form_fields.Required = required;
            return form_fields;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                OnFormIDChanging(value);
                ReportPropertyChanging("FormID");
                _FormID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormID");
                OnFormIDChanged();
            }
        }
        private global::System.Int32 _FormID;
        partial void OnFormIDChanging(global::System.Int32 value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InputType
        {
            get
            {
                return _InputType;
            }
            set
            {
                OnInputTypeChanging(value);
                ReportPropertyChanging("InputType");
                _InputType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InputType");
                OnInputTypeChanged();
            }
        }
        private global::System.String _InputType;
        partial void OnInputTypeChanging(global::System.String value);
        partial void OnInputTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Required
        {
            get
            {
                return _Required;
            }
            set
            {
                OnRequiredChanging(value);
                ReportPropertyChanging("Required");
                _Required = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required");
                OnRequiredChanged();
            }
        }
        private global::System.Boolean _Required;
        partial void OnRequiredChanging(global::System.Boolean value);
        partial void OnRequiredChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="form_responses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class form_responses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new form_responses object.
        /// </summary>
        /// <param name="responseID">Initial value of the ResponseID property.</param>
        /// <param name="formID">Initial value of the FormID property.</param>
        /// <param name="fieldID">Initial value of the FieldID property.</param>
        /// <param name="fieldData">Initial value of the FieldData property.</param>
        public static form_responses Createform_responses(global::System.Int32 responseID, global::System.Int32 formID, global::System.Int32 fieldID, global::System.String fieldData)
        {
            form_responses form_responses = new form_responses();
            form_responses.ResponseID = responseID;
            form_responses.FormID = formID;
            form_responses.FieldID = fieldID;
            form_responses.FieldData = fieldData;
            return form_responses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResponseID
        {
            get
            {
                return _ResponseID;
            }
            set
            {
                if (_ResponseID != value)
                {
                    OnResponseIDChanging(value);
                    ReportPropertyChanging("ResponseID");
                    _ResponseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResponseID");
                    OnResponseIDChanged();
                }
            }
        }
        private global::System.Int32 _ResponseID;
        partial void OnResponseIDChanging(global::System.Int32 value);
        partial void OnResponseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                OnFormIDChanging(value);
                ReportPropertyChanging("FormID");
                _FormID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormID");
                OnFormIDChanged();
            }
        }
        private global::System.Int32 _FormID;
        partial void OnFormIDChanging(global::System.Int32 value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldID
        {
            get
            {
                return _FieldID;
            }
            set
            {
                OnFieldIDChanging(value);
                ReportPropertyChanging("FieldID");
                _FieldID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FieldID");
                OnFieldIDChanged();
            }
        }
        private global::System.Int32 _FieldID;
        partial void OnFieldIDChanging(global::System.Int32 value);
        partial void OnFieldIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FieldData
        {
            get
            {
                return _FieldData;
            }
            set
            {
                OnFieldDataChanging(value);
                ReportPropertyChanging("FieldData");
                _FieldData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FieldData");
                OnFieldDataChanged();
            }
        }
        private global::System.String _FieldData;
        partial void OnFieldDataChanging(global::System.String value);
        partial void OnFieldDataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="news")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class news : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new news object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="headerText">Initial value of the HeaderText property.</param>
        /// <param name="articleContent">Initial value of the ArticleContent property.</param>
        /// <param name="publishDate">Initial value of the PublishDate property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        public static news Createnews(global::System.Int64 id, global::System.String headerText, global::System.String articleContent, global::System.DateTime publishDate, global::System.String category)
        {
            news news = new news();
            news.ID = id;
            news.HeaderText = headerText;
            news.ArticleContent = articleContent;
            news.PublishDate = publishDate;
            news.Category = category;
            return news;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HeaderText
        {
            get
            {
                return _HeaderText;
            }
            set
            {
                OnHeaderTextChanging(value);
                ReportPropertyChanging("HeaderText");
                _HeaderText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HeaderText");
                OnHeaderTextChanged();
            }
        }
        private global::System.String _HeaderText;
        partial void OnHeaderTextChanging(global::System.String value);
        partial void OnHeaderTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ArticleContent
        {
            get
            {
                return _ArticleContent;
            }
            set
            {
                OnArticleContentChanging(value);
                ReportPropertyChanging("ArticleContent");
                _ArticleContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ArticleContent");
                OnArticleContentChanged();
            }
        }
        private global::System.String _ArticleContent;
        partial void OnArticleContentChanging(global::System.String value);
        partial void OnArticleContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PublishDate
        {
            get
            {
                return _PublishDate;
            }
            set
            {
                OnPublishDateChanging(value);
                ReportPropertyChanging("PublishDate");
                _PublishDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishDate");
                OnPublishDateChanged();
            }
        }
        private global::System.DateTime _PublishDate;
        partial void OnPublishDateChanging(global::System.DateTime value);
        partial void OnPublishDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcspro_mvc", Name="photo_propertycache")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class photo_propertycache : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new photo_propertycache object.
        /// </summary>
        /// <param name="filenameHash">Initial value of the FilenameHash property.</param>
        /// <param name="dirHash">Initial value of the DirHash property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        public static photo_propertycache Createphoto_propertycache(global::System.Int32 filenameHash, global::System.Int32 dirHash, global::System.Int16 width, global::System.Int16 height)
        {
            photo_propertycache photo_propertycache = new photo_propertycache();
            photo_propertycache.FilenameHash = filenameHash;
            photo_propertycache.DirHash = dirHash;
            photo_propertycache.Width = width;
            photo_propertycache.Height = height;
            return photo_propertycache;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FilenameHash
        {
            get
            {
                return _FilenameHash;
            }
            set
            {
                if (_FilenameHash != value)
                {
                    OnFilenameHashChanging(value);
                    ReportPropertyChanging("FilenameHash");
                    _FilenameHash = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FilenameHash");
                    OnFilenameHashChanged();
                }
            }
        }
        private global::System.Int32 _FilenameHash;
        partial void OnFilenameHashChanging(global::System.Int32 value);
        partial void OnFilenameHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DirHash
        {
            get
            {
                return _DirHash;
            }
            set
            {
                OnDirHashChanging(value);
                ReportPropertyChanging("DirHash");
                _DirHash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DirHash");
                OnDirHashChanged();
            }
        }
        private global::System.Int32 _DirHash;
        partial void OnDirHashChanging(global::System.Int32 value);
        partial void OnDirHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int16 _Width;
        partial void OnWidthChanging(global::System.Int16 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int16 _Height;
        partial void OnHeightChanging(global::System.Int16 value);
        partial void OnHeightChanged();

        #endregion
    
    }

    #endregion
    
}
